services:
  reader:
    container_name: "comic-reader"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/comic-reader:rw
      - ../../../../data:/data:rw
      - static_volume:/comic-reader/static
    ports:
      - "8000:8000"

volumes:
  static_volume:
