services:
  reader:
    container_name: "comic-reader"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data:/data  # Mount the host's /data directory to the container's /data
    ports:
      - "8000:8000"
    command: ["gunicorn", "--workers=4", "--bind=0.0.0.0:8000", "app:app"]
